version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: aegis_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword123
      POSTGRES_DB: hostel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aegis_backend_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://postgres:postgrespassword123@db:5432/hostel_db?schema=public"
      JWT_SECRET: "super-secret-key-12345!hostel-secret"
      JWT_REFRESH_SECRET: "super-secret-refresh-key-12345!hostel-refresh-secret"
      NODE_ENV: production
      USE_S3: "false"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aegis_frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
